// <auto-generated />
namespace Aula_16_SegundoExercicio.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Migration_Inicial_Criacao_Banco_Mercado : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Migration_Inicial_Criacao_Banco_Mercado));
        
        string IMigrationMetadata.Id
        {
            get { return "201604082004542_Migration_Inicial_Criacao_Banco_Mercado"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
