// <auto-generated />
namespace TreinaWeb.CSAvEx162.Persist.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Criacao_Produto_Venda : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Criacao_Produto_Venda));
        
        string IMigrationMetadata.Id
        {
            get { return "201709131953200_Criacao_Produto_Venda"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
