//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExemploFinal
{
    using System;
    using System.Collections.Generic;
    
    public partial class twc_cursos
    {
        public int twc_id { get; set; }
        public string twc_nome { get; set; }
        public string twc_descricao { get; set; }
    }
}
